In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("datasets\\flavors_of_cocoa.csv")
df.head()

,Id,Company,Bean Origin,Review Date,Cocoa Percent,Company Location,Rating
0,1,A. Morin,Agua Grande,2016.0,63%,France,3.75
1,2,A. Morin,Kpime,2015.0,70%,France,2.75
2,3,A. Morin,Atsane,2015.0,70%,France,3.00
3,4,A. Morin,Akata,2015.0,70%,France,3.50
4,5,A. Morin,Quilla,2015.0,70%,France,3.50

In [5]:
df.isna().sum()

Id                  0
Company             0
Bean Origin         0
Review Date         4
Cocoa Percent       0
Company Location    0
Rating              0
dtype: int64

In [8]:
df['Company Location'].value_counts().head()

Company Location
U.S.A.    764
France    156
Canada    125
U.K.       96
Italy      63
Name: count, dtype: int64

In [10]:
df['Rating'].max()

np.float64(5.0)

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1795 entries, 0 to 1794
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Id                1795 non-null   int64
 1   Company           1795 non-null   str
 2   Bean Origin       1795 non-null   str
 3   Review Date       1791 non-null   float64
 4   Cocoa Percent     1795 non-null   str
 5   Company Location  1795 non-null   str
 6   Rating            1795 non-null   float64
dtypes: float64(2), int64(1), str(4)
memory usage: 98.3 KB

In [12]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[::2])

[1 3 5]

In [13]:
B = np.nan
type(B)

float

In [14]:
df[['Id']]

        Id
0        1
1        2
2        3
3        4
4        5
...    ...
1790  1791
1791  1792
1792  1793
1793  1794
1794  1795

[1795 rows x 1 columns]

In [16]:
df.describe().head()

                Id  Review Date       Rating
count  1795.000000  1791.000000  1795.000000
mean    898.000000  2012.321608     3.185933
std     518.316184     2.928835     0.478062
min       1.000000  2006.000000     1.000000
25%     449.500000  2010.000000     2.875000